export enum Cor{
   // VERMELHO,AMARELO,VERDE,BRANCO,PRETO,AZUL,MARROM,LARANJA,CINZA,ROXO
   VERMELHO = 'VERMELHO',
   AMARELO = 'AMARELO',
   VERDE = 'VERDE',
   PRETO = 'PRETO',
   BRANCO = 'BRANCO',
   ROXO = 'ROXO',
   LARANJA = 'LARANJA',
   AZUL = 'AZUL',
   MARROM = 'MARROM',
   CINZA = 'CINZA'
}